*DECK TAGRES
      SUBROUTINE TAGRES(RES, ALR)
C
C     PACKAGE TAG -- DEUTERON DIS WITH SPECTATOR TAGGING
C     AUTHOR C. WEISS (WEISS.AT.JLAB.ORG)
C
C     USER-DEFINED ROUTINE
C     DEUTERON LIGHT-CONE SPECTRAL FUNCTION
C     RESIDUE AT NUCLEON POLE TPRIME = 0
C     S = RES/(-TPRIME)**2 + LESS SINGULAR
C
C     INPUT:
C     ALR    RECOIL MOMENTUM LIGHT-CONE FRACTION ALPHAR
C
C     OUTPUT:
C     RES    RESIDUE OF SPECTRAL FUNCTION (GEV UNITS)
C
C     V1 13MAY14
C
      IMPLICIT DOUBLE PRECISION (A - H, O - Z)
      PARAMETER (PI = 0.31415 92653 58979 D+01)
      PARAMETER (UN = 0.939D0)
C
C     ...HULTHEN WAVE FUNCTION
C
      A = 0.045647
      B = 0.2719
C
      C = PI**2*(A - B)**2/A/B/(A + B)
C
      EPOL = SQRT(-A**2 + UN**2)
C
C     ...RESIDUE
C
      RES = 4*EPOL/C/ALR
C
      END
C
C---------------------------------------------------------------------
C
