*DECK TAGWD
      SUBROUTINE TAGWD(PSI, AK)
C
C     PACKAGE TAG -- DEUTERON DIS WITH SPECTATOR TAGGING
C     AUTHOR C. WEISS (WEISS.AT.JLAB.ORG)
C
C     USER-DEFINED ROUTINE
C     DEUTERON NON-RELATIVISTIC WAVE FUNCTION PSI-TILDE(K)
C     NORMALIZED SUCH THAT   INTEGRAL (D**3 K) PSI-TILDE(K)**2 = 1
C
C     INPUT:
C     AK   MODULUS OF 3-MOMENTUM K (GEV)
C
C     OUTPUT:
C     PSI  DEUTERON NON-RELATIVISTIC WAVE FUNCTION PSI-TILDE(K)
C
C     ALL DIMENSIONFUL QUANTITIES IN GEV UNITS
C
C     REVISION HISTORY:
C     13MAY14   ORIGINAL CODE
C     31OCT14   CHANGED NAME TO TAGWD (NEW NAMING SCHEME)
C               CHANGED A, B, C TO PARAMETER
C
      IMPLICIT DOUBLE PRECISION (A - H, O - Z)
      PARAMETER (PI = 0.31415 92653 58979 D+01)
C
C     ...TWO-POLE PARAMETRIZATION
C
      PARAMETER (A = 0.045647, 
     *           B = 0.2719,
     *           C = PI**2*(A - B)**2/A/B/(A + B))
C
      PSI = (  1.D0/(AK**2 + A**2)
     *       - 1.D0/(AK**2 + B**2))/SQRT(C)
C
      END
C
C---------------------------------------------------------------------
C
