*DECK TAGFLN
      SUBROUTINE TAGFLN(FL, X, QQ, IPN)
C
C     PACKAGE TAG -- DEUTERON DIS WITH SPECTATOR TAGGING
C     AUTHOR C. WEISS (WEISS.AT.JLAB.ORG)
C
C     USER-DEFINED ROUTINE
C     NUCLEON STRUCTURE FUNCTION FL
C
C     INPUT:
C     X     X VARIABLE FOR NUCLEON
C     QQ    Q2 (GEV**2)
C     IPN   SWITCH: 1  PROTON, 2  NEUTRON
C
C     OUTPUT:
C     FL    NUCLEON STRUCTURE FUNCTION FL
C
C     REVISION HISTORY:
C     31OCT14   FIRST VERSION
C
      IMPLICIT DOUBLE PRECISION (A - H, O - Z)
C
C     ...SIMPLEST APPROXIMATION: SET FL TO ZERO
C
      FL = 0.D0
C
      END
C
C---------------------------------------------------------------------
C
